In [6]:
import numpy as np
MonTableau=np.array([1,2,4])
print (MonTableau)
Montableau2= np.array([[3,4,5],[4,8,1]])
print (Montableau2)

[1 2 4]
[[3 4 5]
 [4 8 1]]


In [8]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
a = np.array([[1, 2], [3, 4], [5,6]])
print (a)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
a = np.array([(1, 2), (3, 4), (5,6)])
print (a)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
a.shape

(3, 2)

In [19]:
a[0,0]
print(a[0,0])

1


In [41]:
#Declaration d'un tableau multidimentionnel
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
print ("Voici mon tableau:",a)
# Connaitre la dimension du tableau 
print("Voici les dimensions de mon tableau:",a.shape)
# Acceder à un élément du tableau ligne 0 et colonne 2 ATTENTION Tableau index démarre à partir de 0
print("On accède à cet élément a[0,2]:",a[0,2])
print("On fait un slicing a[1,:]:",a[1,:])
print("On fait un slicing a[:,2]:",a[:, 2])
#if you dont know how many columns you have dont worry!
print(a[:,-1])


Voici mon tableau: [[0 1 2]
 [3 4 5]
 [6 7 8]]
Voici les dimensions de mon tableau: (3, 3)
On accède à cet élément a[0,2]: 2
On fait un slicing a[1,:]: [3 4 5]
On fait un slicing a[:,2]: [2 5 8]
[2 5 8]
